version: '3.9'
services:
  mongo: 
    image: mongo:4.2.5
    ports:
      - '27019:27017' 

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - WAIT_HOSTS=mongo:27017 
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
