version: '3.8'
services:
  mongo:
    image: mongo:4.2.5
    ports: 
      - '27018:27017'
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - WAIT_HOSTS=mongo:27017

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
