version: '3.8'
services:
  mongo:
    image: mongo:4.2.5
    ports: 
      - '27019:27017'
  flaskapp:
    build: ./backend
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - WAIT_HOSTS=mongo:27017

