version: '3.8'
services:
  mongo:
    image: mongo:4.2.5
  flaskapp:
    build: ./api
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - WAIT_HOSTS=mongo:27017
  nginx:
    build: ./nginx
    ports:  
      - "80:80"
